<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // International dialing codes keyed by ISO 3166-1 alpha-2 code (the `code` column).
        $phoneCodes = [
            'AF' => '+93', 'AX' => '+358', 'AL' => '+355', 'DZ' => '+213', 'AS' => '+1', 'AD' => '+376',
            'AO' => '+244', 'AI' => '+1', 'AQ' => '+672', 'AG' => '+1', 'AR' => '+54', 'AM' => '+374',
            'AW' => '+297', 'AU' => '+61', 'AT' => '+43', 'AZ' => '+994', 'BS' => '+1', 'BH' => '+973',
            'BD' => '+880', 'BB' => '+1', 'BY' => '+375', 'BE' => '+32', 'BZ' => '+501', 'BJ' => '+229',
            'BM' => '+1', 'BT' => '+975', 'BO' => '+591', 'BQ' => '+599', 'BA' => '+387', 'BW' => '+267',
            'BV' => '+47', 'BR' => '+55', 'IO' => '+246', 'BN' => '+673', 'BG' => '+359', 'BF' => '+226',
            'BI' => '+257', 'KH' => '+855', 'CM' => '+237', 'CA' => '+1', 'CV' => '+238', 'KY' => '+1',
            'CF' => '+236', 'TD' => '+235', 'CL' => '+56', 'CN' => '+86', 'CX' => '+61', 'CC' => '+61',
            'CO' => '+57', 'KM' => '+269', 'CG' => '+242', 'CD' => '+243', 'CK' => '+682', 'CR' => '+506',
            'CI' => '+225', 'HR' => '+385', 'CU' => '+53', 'CW' => '+599', 'CY' => '+357', 'CZ' => '+420',
            'DK' => '+45', 'DJ' => '+253', 'DM' => '+1', 'DO' => '+1', 'EC' => '+593', 'EG' => '+20',
            'SV' => '+503', 'GQ' => '+240', 'ER' => '+291', 'EE' => '+372', 'ET' => '+251', 'FK' => '+500',
            'FO' => '+298', 'FJ' => '+679', 'FI' => '+358', 'FR' => '+33', 'GF' => '+594', 'PF' => '+689',
            'TF' => '+262', 'GA' => '+241', 'GM' => '+220', 'GE' => '+995', 'DE' => '+49', 'GH' => '+233',
            'GI' => '+350', 'GR' => '+30', 'GL' => '+299', 'GD' => '+1', 'GP' => '+590', 'GU' => '+1',
            'GT' => '+502', 'GG' => '+44', 'GN' => '+224', 'GW' => '+245', 'GY' => '+592', 'HT' => '+509',
            'HM' => '+672', 'VA' => '+379', 'HN' => '+504', 'HK' => '+852', 'HU' => '+36', 'IS' => '+354',
            'IN' => '+91', 'ID' => '+62', 'IR' => '+98', 'IQ' => '+964', 'IE' => '+353', 'IM' => '+44',
            'IL' => '+972', 'IT' => '+39', 'JM' => '+1', 'JP' => '+81', 'JE' => '+44', 'JO' => '+962',
            'KZ' => '+7', 'KE' => '+254', 'KI' => '+686', 'KP' => '+850', 'KR' => '+82', 'KW' => '+965',
            'KG' => '+996', 'LA' => '+856', 'LV' => '+371', 'LB' => '+961', 'LS' => '+266', 'LR' => '+231',
            'LY' => '+218', 'LI' => '+423', 'LT' => '+370', 'LU' => '+352', 'MO' => '+853', 'MK' => '+389',
            'MG' => '+261', 'MW' => '+265', 'MY' => '+60', 'MV' => '+960', 'ML' => '+223', 'MT' => '+356',
            'MH' => '+692', 'MQ' => '+596', 'MR' => '+222', 'MU' => '+230', 'YT' => '+262', 'MX' => '+52',
            'FM' => '+691', 'MD' => '+373', 'MC' => '+377', 'MN' => '+976', 'ME' => '+382', 'MS' => '+1',
            'MA' => '+212', 'MZ' => '+258', 'MM' => '+95', 'NA' => '+264', 'NR' => '+674', 'NP' => '+977',
            'NL' => '+31', 'NC' => '+687', 'NZ' => '+64', 'NI' => '+505', 'NE' => '+227', 'NG' => '+234',
            'NU' => '+683', 'NF' => '+672', 'MP' => '+1', 'NO' => '+47', 'OM' => '+968', 'PK' => '+92',
            'PW' => '+680', 'PS' => '+970', 'PA' => '+507', 'PG' => '+675', 'PY' => '+595', 'PE' => '+51',
            'PH' => '+63', 'PN' => '+64', 'PL' => '+48', 'PT' => '+351', 'PR' => '+1', 'QA' => '+974',
            'RE' => '+262', 'RO' => '+40', 'RU' => '+7', 'RW' => '+250', 'BL' => '+590', 'SH' => '+290',
            'KN' => '+1', 'LC' => '+1', 'MF' => '+590', 'PM' => '+508', 'VC' => '+1', 'WS' => '+685',
            'SM' => '+378', 'ST' => '+239', 'SA' => '+966', 'SN' => '+221', 'RS' => '+381', 'SC' => '+248',
            'SL' => '+232', 'SG' => '+65', 'SX' => '+1', 'SK' => '+421', 'SI' => '+386', 'SB' => '+677',
            'SO' => '+252', 'ZA' => '+27', 'GS' => '+500', 'SS' => '+211', 'ES' => '+34', 'LK' => '+94',
            'SD' => '+249', 'SR' => '+597', 'SJ' => '+47', 'SZ' => '+268', 'SE' => '+46', 'CH' => '+41',
            'SY' => '+963', 'TW' => '+886', 'TJ' => '+992', 'TZ' => '+255', 'TH' => '+66', 'TL' => '+670',
            'TG' => '+228', 'TK' => '+690', 'TO' => '+676', 'TT' => '+1', 'TN' => '+216', 'TR' => '+90',
            'TM' => '+993', 'TC' => '+1', 'TV' => '+688', 'UG' => '+256', 'UA' => '+380', 'AE' => '+971',
            'GB' => '+44', 'US' => '+1', 'UM' => '+1', 'UY' => '+598', 'UZ' => '+998', 'VU' => '+678',
            'VE' => '+58', 'VN' => '+84', 'VG' => '+1', 'VI' => '+1', 'WF' => '+681', 'EH' => '+212',
            'YE' => '+967', 'ZM' => '+260', 'ZW' => '+263',
        ];

        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
        Schema::enableForeignKeyConstraints();

        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'nationality' => 'Afghan', 'currency' => '؋', 'currency_code' => 'AFN', 'flag' => 'countries/32x32/af.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Åland Islands', 'code' => 'AX', 'nationality' => 'Åland Island', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/ax.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Albania', 'code' => 'AL', 'nationality' => 'Albanian', 'currency' => 'Lek', 'currency_code' => 'ALL', 'flag' => 'countries/32x32/al.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Algeria', 'code' => 'DZ', 'nationality' => 'Algerian', 'currency' => 'دج', 'currency_code' => 'DZD', 'flag' => 'countries/32x32/dz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'American Samoa', 'code' => 'AS', 'nationality' => 'American Samoan', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/as.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Andorra', 'code' => 'AD', 'nationality' => 'Andorran', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/ad.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Angola', 'code' => 'AO', 'nationality' => 'Angolan', 'currency' => 'Kz', 'currency_code' => 'AOA', 'flag' => 'countries/32x32/ao.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Anguilla', 'code' => 'AI', 'nationality' => 'Anguillan', 'currency' => '$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/ai.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Antarctica', 'code' => 'AQ', 'nationality' => 'Antarctic', 'currency' => '', 'currency_code' => '', 'flag' => 'countries/32x32/aq.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'nationality' => 'Antiguan or Barbudan', 'currency' => '$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/ag.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Argentina', 'code' => 'AR', 'nationality' => 'Argentine, Argentinian', 'currency' => '$', 'currency_code' => 'ARS', 'flag' => 'countries/32x32/ar.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Armenia', 'code' => 'AM', 'nationality' => 'Armenian',  'currency' => '֏', 'currency_code' => 'AMD', 'flag' => 'countries/32x32/am.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Aruba', 'code' => 'AW', 'nationality' => 'Aruban', 'cur rency' => 'ƒ', 'currency_code' => 'AMD', 'flag' => 'countries/32x32/aw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Australia', 'code' => 'AU', 'nationality' => 'Australian', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/au.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Austria', 'code' => 'AT', 'nationality' => 'Austrian', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/at.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'nationality' => 'Azerbaijani, Azeri', 'currency' => '₼', 'currency_code' => 'AZN', 'flag' => 'countries/32x32/az.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bahamas', 'code' => 'BS', 'nationality' => 'Bahamian', 'currency' => 'B$', 'currency_code' => 'BSD', 'flag' => 'countries/32x32/bs.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bahrain', 'code' => 'BH', 'nationality' => 'Bahraini', 'currency' => '.د.ب', 'currency_code' => 'BHD', 'flag' => 'countries/32x32/bh.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bangladesh', 'code' => 'BD', 'nationality' => 'Bangladeshi', 'currency' => '৳', 'currency_code' => 'BDT', 'flag' => 'countries/32x32/bd.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Barbados', 'code' => 'BB', 'nationality' => 'Barbadian', 'currency' => 'Bds$', 'currency_code' => 'BBD', 'flag' => 'countries/32x32/bb.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Belarus', 'code' => 'BY', 'nationality' => 'Belarusian', 'currency' => 'Br', 'currency_code' => 'BYN', 'flag' => 'countries/32x32/by.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Belgium', 'code' => 'BE', 'nationality' => 'Belgian', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/be.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Belize', 'code' => 'BZ', 'nationality' => 'Belizean', 'currency' => '$', 'currency_code' => 'BZD', 'flag' => 'countries/32x32/bz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Benin', 'code' => 'BJ', 'nationality' => 'Beninese, Beninois', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/bj.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bermuda', 'code' => 'BM', 'nationality' => 'Bermudian, Bermudan', 'currency' => '$', 'currency_code' => 'BMD', 'flag' => 'countries/32x32/bm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bhutan', 'code' => 'BT', 'nationality' => 'Bhutanese', 'currency' => 'Nu', 'currency_code' => 'BTN', 'flag' => 'countries/32x32/bt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'nationality' => 'Bolivian', 'currency' => 'Bs', 'currency_code' => 'BOB', 'flag' => 'countries/32x32/bo.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'nationality' => 'Bonaire', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/bq.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'nationality' => 'Bosnian, Herzegovinian', 'currency' => 'KM', 'currency_code' => 'BAM', 'flag' => 'countries/32x32/ba.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Botswana', 'code' => 'BW', 'nationality' => 'Motswana, Botswanan', 'currency' => 'P', 'currency_code' => 'BWP', 'flag' => 'countries/32x32/bw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'nationality' => 'Bouvet Island', 'currency' => '', 'currency_code' => '', 'flag' => 'countries/32x32/bv.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Brazil', 'code' => 'BR', 'nationality' => 'Brazilian', 'currency' => 'R$', 'currency_code' => 'BRL', 'flag' => 'countries/32x32/br.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'nationality' => 'BIOT', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/io.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'nationality' => 'Bruneian', 'currency' => 'B$', 'currency_code' => 'BND', 'flag' => 'countries/32x32/bn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Bulgaria', 'code' => 'BG', 'nationality' => 'Bulgarian', 'currency' => 'Лв', 'currency_code' => 'BGN', 'flag' => 'countries/32x32/bg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'nationality' => 'Burkinabé', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/bf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Burundi', 'code' => 'BI', 'nationality' => 'Burundian', 'currency' => 'FBu', 'currency_code' => 'BIF', 'flag' => 'countries/32x32/bi.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cambodia', 'code' => 'KH', 'nationality' => 'Cambodian', 'currency' => '៛', 'currency_code' => 'KHR', 'flag' => 'countries/32x32/kh.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cameroon', 'code' => 'CM', 'nationality' => 'Cameroonian', 'currency' => 'FCFA', 'currency_code' => 'XAF', 'flag' => 'countries/32x32/cm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Canada', 'code' => 'CA', 'nationality' => 'Canadian', 'currency' => '$', 'currency_code' => 'CAD', 'flag' => 'countries/32x32/ca.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cape Verde', 'code' => 'CV', 'nationality' => 'Cape Verdean', 'currency' => '$', 'currency_code' => 'CVE', 'flag' => 'countries/32x32/cv.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'nationality' => 'Caymanian', 'currency' => '$', 'currency_code' => 'KYD', 'flag' => 'countries/32x32/ky.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Central African Republic', 'code' => 'CF', 'nationality' => 'Central African', 'currency' => 'FCFA', 'currency_code' => 'CFA', 'flag' => 'countries/32x32/cf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Chad', 'code' => 'TD', 'nationality' => 'Chadian', 'currency' => 'FCFA', 'currency_code' => 'XAF', 'flag' => 'countries/32x32/td.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Chile', 'code' => 'CL', 'nationality' => 'Chilean', 'currency' => '$', 'currency_code' => 'CLP', 'flag' => 'countries/32x32/cl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'China', 'code' => 'CN', 'nationality' => 'Chinese', 'currency' => '¥', 'currency_code' => 'CNY', 'flag' => 'countries/32x32/cn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Christmas Island', 'code' => 'CX', 'nationality' => 'Chirstman Island', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/cx.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'nationality' => 'Cocos Island', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/cc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Colombia', 'code' => 'CO', 'nationality' => 'Colombian', 'currency' => '$', 'currency_code' => 'COP', 'flag' => 'countries/32x32/co.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Comoros', 'code' => 'KM', 'nationality' => 'Comorian', 'currency' => 'CF', 'currency_code' => 'KMF', 'flag' => 'countries/32x32/km.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Congo', 'code' => 'CG', 'nationality' => 'Congolese', 'currency' => 'FC', 'currency_code' => 'CDF', 'flag' => 'countries/32x32/cg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'nationality' => 'Congolese', 'currency' => 'FC', 'currency_code' => 'CDF', 'flag' => 'countries/32x32/cd.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cook Islands', 'code' => 'CK', 'nationality' => 'Cook Island', 'currency' => '$', 'currency_code' => 'NZD', 'flag' => 'countries/32x32/ck.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Costa Rica', 'code' => 'CR', 'nationality' => 'Costa Ricam', 'currency' => '₡', 'currency_code' => 'CRC', 'flag' => 'countries/32x32/cr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'nationality' => 'Ivorian', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/ci.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Croatia', 'code' => 'HR', 'nationality' => 'Croatian', 'currency' => 'kn', 'currency_code' => 'HRK', 'flag' => 'countries/32x32/hr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cuba', 'code' => 'CU', 'nationality' => 'Cuban', 'currency' => '$', 'currency_code' => 'CUP', 'flag' => 'countries/32x32/cu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Curaçao', 'code' => 'CW', 'nationality' => 'Curaçaoan', 'currency' => 'NAF', 'currency_code' => 'ANG', 'flag' => 'countries/32x32/cw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Cyprus', 'code' => 'CY', 'nationality' => 'Cypriot', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/cy.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'nationality' => 'Czech', 'currency' => 'Kč', 'currency_code' => 'CZK', 'flag' => 'countries/32x32/cz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Denmark', 'code' => 'DK', 'nationality' => 'Danish', 'currency' => 'Kr', 'currency_code' => 'CZK', 'flag' => 'countries/32x32/dk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Djibouti', 'code' => 'DJ', 'nationality' => 'Djiboutian', 'currency' => 'Fdj', 'currency_code' => 'DJF', 'flag' => 'countries/32x32/dj.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Dominica', 'code' => 'DM', 'nationality' => 'Dominican', 'currency' => '$', 'currency_code' => 'DOP', 'flag' => 'countries/32x32/dm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'nationality' => 'Dominican', 'currency' => '$', 'currency_code' => 'DOP', 'flag' => 'countries/32x32/do.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Ecuador', 'code' => 'EC', 'nationality' => 'Ecuadorian', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/ec.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Egypt', 'code' => 'EG', 'nationality' => 'Egyptian', 'currency' => 'E£', 'currency_code' => 'EGP', 'flag' => 'countries/32x32/eg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'El Salvador', 'code' => 'SV', 'nationality' => 'Salvadoran', 'currency' => 'SVC', 'currency_code' => 'SVC', 'flag' => 'countries/32x32/sv.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'nationality' => 'Equatorial Guinean, Equatoguinean', 'currency' => 'FCFA', 'currency_code' => 'XAF', 'flag' => 'countries/32x32/gq.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Eritrea', 'code' => 'ER', 'nationality' => 'Eritrean', 'currency' => 'NFk', 'currency_code' => 'ERN', 'flag' => 'countries/32x32/er.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Estonia', 'code' => 'EE', 'nationality' => 'Estonian', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/ee.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Ethiopia', 'code' => 'ET', 'nationality' => 'Ethiopian', 'currency' => 'Br', 'currency_code' => 'ETB', 'flag' => 'countries/32x32/et.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'nationality' => 'Falkland Island"', 'currency' => '£', 'currency_code' => 'FKP', 'flag' => 'countries/32x32/fk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'nationality' => 'Faroese', 'currency' => 'kr', 'currency_code' => 'FOK', 'flag' => 'countries/32x32/fo.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Fiji', 'code' => 'FJ', 'nationality' => 'Fijian', 'currency' => 'FJD', 'currency_code' => 'FJD', 'flag' => 'countries/32x32/fk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Finland', 'code' => 'FI', 'nationality' => 'Finnish', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/fi.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'France', 'code' => 'FR', 'nationality' => 'French', 'currency' => '₣', 'currency_code' => 'XPF', 'flag' => 'countries/32x32/fr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'French Guiana', 'code' => 'GF', 'nationality' => 'French Guianese', 'currency' => '₣', 'currency_code' => 'XPF', 'flag' => 'countries/32x32/gf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'French Polynesia', 'code' => 'PF', 'nationality' => 'French Polynesian', 'currency' => '₣', 'currency_code' => 'XPF', 'flag' => 'countries/32x32/pf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'nationality' => 'French Southern Territories', 'currency' => '₣', 'currency_code' => 'XPF', 'flag' => 'countries/32x32/tf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Gabon', 'code' => 'GA', 'nationality' => 'Gabonese', 'currency' => 'FCFA', 'currency_code' => 'XAF', 'flag' => 'countries/32x32/ga.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Gambia', 'code' => 'GM', 'nationality' => 'Gambian', 'currency' => 'D', 'currency_code' => 'GMD', 'flag' => 'countries/32x32/gm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Georgia', 'code' => 'GE', 'nationality' => 'Georgian', 'currency' => 'GEL', 'currency_code' => 'GEL', 'flag' => 'countries/32x32/ge.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Germany', 'code' => 'DE', 'nationality' => 'German', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/de.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Ghana', 'code' => 'GH', 'nationality' => 'Ghanaian', 'currency' => 'GH₵', 'currency_code' => 'GHS', 'flag' => 'countries/32x32/gh.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Gibraltar', 'code' => 'GI', 'nationality' => 'Gibraltar', 'currency' => '£', 'currency_code' => 'GIP', 'flag' => 'countries/32x32/gi.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Greece', 'code' => 'GR', 'nationality' => 'Greek, Hellenic', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/gr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Greenland', 'code' => 'GL', 'nationality' => 'Greenlandic', 'currency' => 'Kr.', 'currency_code' => 'DKK', 'flag' => 'countries/32x32/gl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Grenada', 'code' => 'GD', 'nationality' => 'Grenadian', 'currency' => 'EC$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/gd.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'nationality' => 'Guadeloupe', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/gp.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guam', 'code' => 'GU', 'nationality' => 'Guamanian, Guambat', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/gu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guatemala', 'code' => 'GT', 'nationality' => 'Guatemalan', 'currency' => 'Q', 'currency_code' => 'GTQ', 'flag' => 'countries/32x32/gt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guernsey', 'code' => 'GG', 'nationality' => 'Channel Island', 'currency' => '£', 'currency_code' => 'GGP', 'flag' => 'countries/32x32/gg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guinea', 'code' => 'GN', 'nationality' => 'Guinean', 'currency' => 'FG', 'currency_code' => 'GNF', 'flag' => 'countries/32x32/gn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'nationality' => 'Bissau-Guinean', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/gw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Guyana', 'code' => 'GY', 'nationality' => 'Guyanese', 'currency' => '$', 'currency_code' => 'GYD', 'flag' => 'countries/32x32/gy.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Haiti', 'code' => 'HT', 'nationality' => 'Haitian', 'currency' => 'G', 'currency_code' => 'HTG', 'flag' => 'countries/32x32/ht.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM', 'nationality' => 'Heard Island or McDonald Islands', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/hm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'nationality' => 'Vatican', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/va.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Honduras', 'code' => 'HN', 'nationality' => 'Honduran', 'currency' => 'L', 'currency_code' => 'HNL', 'flag' => 'countries/32x32/hn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Hong Kong', 'code' => 'HK', 'nationality' => 'Hong Kong, Hong Kongese', 'currency' => '$', 'currency_code' => 'HKD', 'flag' => 'countries/32x32/hk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Hungary', 'code' => 'HU', 'nationality' => 'Hungarian, Magyar', 'currency' => 'Ft', 'currency_code' => 'HUF', 'flag' => 'countries/32x32/hu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Iceland', 'code' => 'IS', 'nationality' => 'Icelandic', 'currency' => 'Kr', 'currency_code' => 'ISK', 'flag' => 'countries/32x32/is.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'India', 'code' => 'IN', 'nationality' => 'Indian', 'currency' => '₹', 'currency_code' => 'INR', 'flag' => 'countries/32x32/in.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Indonesia', 'code' => 'ID', 'nationality' => 'Indonesian', 'currency' => 'Rp', 'currency_code' => 'IDR', 'flag' => 'countries/32x32/id.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'nationality' => 'Iranian, Persian', 'currency' => '﷼', 'currency_code' => 'IRR', 'flag' => 'countries/32x32/ir.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Iraq', 'code' => 'IQ', 'nationality' => 'Iraqi', 'currency' => 'ع.د', 'currency_code' => 'IQD', 'flag' => 'countries/32x32/iq.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Ireland', 'code' => 'IE', 'nationality' => 'Irish', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/ie.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Isle of Man', 'code' => 'IM', 'nationality' => 'Manx', 'currency' => '£', 'currency_code' => 'IMP', 'flag' => 'countries/32x32/im.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Israel', 'code' => 'IL', 'nationality' => 'Israeli', 'currency' => '₪', 'currency_code' => 'ILS', 'flag' => 'countries/32x32/il.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Italy', 'code' => 'IT', 'nationality' => 'Italian', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/it.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Jamaica', 'code' => 'JM', 'nationality' => 'Jamaican', 'currency' => '$', 'currency_code' => 'JMD', 'flag' => 'countries/32x32/jm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Japan', 'code' => 'JP', 'nationality' => 'Japanese', 'currency' => '¥', 'currency_code' => 'JYP', 'flag' => 'countries/32x32/jp.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Jersey', 'code' => 'JE', 'nationality' => 'Channel Island', 'currency' => '£', 'currency_code' => 'JEP', 'flag' => 'countries/32x32/je.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Jordan', 'code' => 'JO', 'nationality' => 'Jordanian', 'currency' => 'د.ا', 'currency_code' => 'JOD', 'flag' => 'countries/32x32/jo.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'nationality' => 'Kazakhstani, Kazakh', 'currency' => '₸', 'currency_code' => 'KZT', 'flag' => 'countries/32x32/kz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Kenya', 'code' => 'KE', 'nationality' => 'Kenyan', 'currency' => 'Ksh', 'currency_code' => 'KES', 'flag' => 'countries/32x32/ke.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Kiribati', 'code' => 'KI', 'nationality' => 'I-Kiribati', 'currency' => '$', 'currency_code' => 'KID', 'flag' => 'countries/32x32/ki.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'nationality' => 'North Korean', 'currency' => '₩', 'currency_code' => 'KPW', 'flag' => 'countries/32x32/kp.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'nationality' => 'South Korean', 'currency' => '₩', 'currency_code' => 'KRW', 'flag' => 'countries/32x32/kr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Kuwait', 'code' => 'KW', 'nationality' => 'Kuwaiti', 'currency' => 'KD', 'currency_code' => 'KWD', 'flag' => 'countries/32x32/kw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'nationality' => 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz', 'currency' => 'Лв', 'currency_code' => 'KGS', 'flag' => 'countries/32x32/kg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'nationality' => 'Lao, Laotian', 'currency' => '₭', 'currency_code' => 'LAK', 'flag' => 'countries/32x32/la.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Latvia', 'code' => 'LV', 'nationality' => 'Latvian', 'currency' => 'Ls', 'currency_code' => 'LVL', 'flag' => 'countries/32x32/lv.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Lebanon', 'code' => 'LB', 'nationality' => 'Lebanese', 'currency' => 'ل.ل', 'currency_code' => 'LBP', 'flag' => 'countries/32x32/lb.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Lesotho', 'code' => 'LS', 'nationality' => 'Basotho', 'currency' => 'L', 'currency_code' => 'LSL', 'flag' => 'countries/32x32/ls.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Liberia', 'code' => 'LR', 'nationality' => 'Liberian', 'currency' => 'L$', 'currency_code' => 'LRD', 'flag' => 'countries/32x32/lr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Libya', 'code' => 'LY', 'nationality' => 'Libyan', 'currency' => 'LD', 'currency_code' => 'LYD', 'flag' => 'countries/32x32/ly.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'nationality' => 'Liechtenstein', 'currency' => 'Chf', 'currency_code' => 'CHF', 'flag' => 'countries/32x32/li.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Lithuania', 'code' => 'LT', 'nationality' => 'Lithuanian', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/lt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Luxembourg', 'code' => 'LU', 'nationality' => 'Luxembourg, Luxembourgish', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/lu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Macao', 'code' => 'MO', 'nationality' => 'Macanese, Chinese', 'currency' => 'MOP$', 'currency_code' => 'MOP', 'flag' => 'countries/32x32/mo.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'nationality' => 'Macedonian', 'currency' => 'Ден', 'currency_code' => 'MKD', 'flag' => 'countries/32x32/mk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Madagascar', 'code' => 'MG', 'nationality' => 'Malagasy', 'currency' => 'Ar', 'currency_code' => 'MGA', 'flag' => 'countries/32x32/mg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Malawi', 'code' => 'MW', 'nationality' => 'Malawian', 'currency' => 'MK', 'currency_code' => 'MWK', 'flag' => 'countries/32x32/mw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Malaysia', 'code' => 'MY', 'nationality' => 'Malaysian', 'currency' => 'RM', 'currency_code' => 'MYR', 'flag' => 'countries/32x32/my.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Maldives', 'code' => 'MV', 'nationality' => 'Maldivian', 'currency' => 'Rf', 'currency_code' => 'MVR', 'flag' => 'countries/32x32/mv.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mali', 'code' => 'ML', 'nationality' => 'Malian, Malinese', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/ml.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Malta', 'code' => 'MT', 'nationality' => 'Maltese', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/mt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'nationality' => 'Marshallese', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/mh.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Martinique', 'code' => 'MQ', 'nationality' => 'Martiniquais, Martinican', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/mq.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mauritania', 'code' => 'MR', 'nationality' => 'Mauritanian', 'currency' => 'UM', 'currency_code' => 'MRU', 'flag' => 'countries/32x32/mr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mauritius', 'code' => 'MU', 'nationality' => 'Mauritian', 'currency' => 'Rs', 'currency_code' => 'MUR', 'flag' => 'countries/32x32/mu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mayotte', 'code' => 'YT', 'nationality' => 'Mahoran', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/yt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mexico', 'code' => 'MX', 'nationality' => 'Mexican', 'currency' => '$', 'currency_code' => 'MXN', 'flag' => 'countries/32x32/mx.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'nationality' => 'Micronesian', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/fm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'nationality' => 'Moldovan', 'currency' => 'L', 'currency_code' => 'MDL', 'flag' => 'countries/32x32/md.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Monaco', 'code' => 'MC', 'nationality' => 'Monacan', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/mc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mongolia', 'code' => 'MN', 'nationality' => 'Mongolian', 'currency' => '₮', 'currency_code' => 'MNT', 'flag' => 'countries/32x32/mn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Montenegro', 'code' => 'ME', 'nationality' => 'Montenegrin', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/me.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Montserrat', 'code' => 'MS', 'nationality' => 'Montserratian', 'currency' => '$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/ms.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Morocco', 'code' => 'MA', 'nationality' => 'Moroccan', 'currency' => 'MAD', 'currency_code' => 'MAD', 'flag' => 'countries/32x32/ma.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mozambique', 'code' => 'MZ', 'nationality' => 'Mozambican', 'currency' => 'Mt', 'currency_code' => 'MZN', 'flag' => 'countries/32x32/mz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Myanmar', 'code' => 'MM', 'nationality' => 'Burmese', 'currency' => 'K', 'currency_code' => 'MMK', 'flag' => 'countries/32x32/mm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Namibia', 'code' => 'NA', 'nationality' => 'Namibian', 'currency' => '$', 'currency_code' => 'NAD', 'flag' => 'countries/32x32/na.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Nauru', 'code' => 'NR', 'nationality' => 'Nauruan', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/nr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Nepal', 'code' => 'NP', 'nationality' => 'Nepali, Nepalese', 'currency' => 'Rs.', 'currency_code' => 'NPR', 'flag' => 'countries/32x32/np.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Netherlands', 'code' => 'NL', 'nationality' => 'Dutch, Netherlandic', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/nl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'New Caledonia', 'code' => 'NC', 'nationality' => 'New Caledonian', 'currency' => 'F', 'currency_code' => 'XPF', 'flag' => 'countries/32x32/nc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'New Zealand', 'code' => 'NZ', 'nationality' => 'New Zealand, NZ', 'currency' => '$', 'currency_code' => 'NZD', 'flag' => 'countries/32x32/nz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Nicaragua', 'code' => 'NI', 'nationality' => 'Nicaraguan', 'currency' => 'C$', 'currency_code' => 'NIO', 'flag' => 'countries/32x32/ni.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Niger', 'code' => 'NE', 'nationality' => 'Nigerien', 'currency' => '₦', 'currency_code' => 'NGN', 'flag' => 'countries/32x32/ne.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Nigeria', 'code' => 'NG', 'nationality' => 'Nigerian', 'currency' => '₦', 'currency_code' => 'NGN', 'flag' => 'countries/32x32/ng.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Niue', 'code' => 'NU', 'nationality' => 'Niuean', 'currency' => '$', 'currency_code' => 'NZD', 'flag' => 'countries/32x32/nu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'nationality' => 'Norfolk Island', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/nf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'nationality' => 'Northern Marianan', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/mp.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Norway', 'code' => 'NO', 'nationality' => 'Norwegian', 'currency' => 'Kr', 'currency_code' => 'NOK', 'flag' => 'countries/32x32/no.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Oman', 'code' => 'OM', 'nationality' => 'Omani', 'currency' => 'ر.ع.', 'currency_code' => 'OMR', 'flag' => 'countries/32x32/om.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Pakistan', 'code' => 'PK', 'nationality' => 'Pakistani', 'currency' => 'Rs', 'currency_code' => 'PKR', 'flag' => 'countries/32x32/pk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Palau', 'code' => 'PW', 'nationality' => 'Palauan', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/pw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'nationality' => 'Palestinian', 'currency' => '£', 'currency_code' => 'JOD', 'flag' => 'countries/32x32/ps.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Panama', 'code' => 'PA', 'nationality' => 'Panamanian', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/pa.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'nationality' => 'Papua New Guinean, Papuan', 'currency' => 'K', 'currency_code' => 'PGK', 'flag' => 'countries/32x32/pg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Paraguay', 'code' => 'PY', 'nationality' => 'Paraguayan', 'currency' => '₲', 'currency_code' => 'PYG', 'flag' => 'countries/32x32/nl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Peru', 'code' => 'PE', 'nationality' => 'Peruvian', 'currency' => 'S/', 'currency_code' => 'PEN', 'flag' => 'countries/32x32/PE.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Philippines', 'code' => 'PH', 'nationality' => 'Philippine, Filipino', 'currency' => '₱', 'currency_code' => 'PHP', 'flag' => 'countries/32x32/ph.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Pitcairn', 'code' => 'PN', 'nationality' => 'Pitcairn Island', 'currency' => '$', 'currency_code' => 'NZD', 'flag' => 'countries/32x32/pn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Poland', 'code' => 'PL', 'nationality' => 'Polish', 'currency' => 'zł', 'currency_code' => 'PLN', 'flag' => 'countries/32x32/pl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Portugal', 'code' => 'PT', 'nationality' => 'Portuguese', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/pt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'nationality' => 'Puerto Rican', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/pt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Qatar', 'code' => 'QA', 'nationality' => 'Qatari', 'currency' => 'QR', 'currency_code' => 'QAR', 'flag' => 'countries/32x32/qa.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Réunion', 'code' => 'RE', 'nationality' => 'Réunionese, Réunionnais', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/re.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Romania', 'code' => 'RO', 'nationality' => 'Romanian', 'currency' => 'lei', 'currency_code' => 'RON', 'flag' => 'countries/32x32/ro.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Russian Federation', 'code' => 'RU', 'nationality' => 'Russian', 'currency' => '₽', 'currency_code' => 'RUB', 'flag' => 'countries/32x32/ru.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Rwanda', 'code' => 'RW', 'nationality' => 'Rwandan', 'currency' => 'RF', 'currency_code' => 'RWF', 'flag' => 'countries/32x32/rw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'nationality' => 'Barthélemois', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/bl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'nationality' => 'Saint Helenian', 'currency' => '£', 'currency_code' => 'SHP', 'flag' => 'countries/32x32/sh.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'nationality' => 'Kittitian or Nevisian', 'currency' => '$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/kn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'nationality' => 'Saint Lucian', 'currency' => '$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/lc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'nationality' => 'Saint-Martinoise', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/mf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'nationality' => 'Saint-Pierrais or Miquelonnais', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/pm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'nationality' => 'Saint Vincentian, Vincentian', 'currency' => '$', 'currency_code' => 'XCD', 'flag' => 'countries/32x32/vc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Samoa', 'code' => 'WS', 'nationality' => 'Samoan', 'currency' => 'WS$', 'currency_code' => 'WST', 'flag' => 'countries/32x32/ws.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'San Marino', 'code' => 'SM', 'nationality' => 'Sammarinese', 'currency' => '₤', 'currency_code' => 'SML', 'flag' => 'countries/32x32/sm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'nationality' => 'São Toméan', 'currency' => 'Db', 'currency_code' => 'STD', 'flag' => 'countries/32x32/st.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'nationality' => 'Saudi, Saudi Arabian', 'currency' => 'SR', 'currency_code' => 'SAR', 'flag' => 'countries/32x32/sa.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Senegal', 'code' => 'SN', 'nationality' => 'Senegalese', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/sn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Serbia', 'code' => 'RS', 'nationality' => 'Serbian', 'currency' => 'din', 'currency_code' => 'RSD', 'flag' => 'countries/32x32/rs.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Seychelles', 'code' => 'SC', 'nationality' => 'Seychellois', 'currency' => 'Rs', 'currency_code' => 'SCR', 'flag' => 'countries/32x32/sc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'nationality' => 'Sierra Leonean', 'currency' => 'Le', 'currency_code' => 'SLL', 'flag' => 'countries/32x32/sl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Singapore', 'code' => 'SG', 'nationality' => 'Singaporean', 'currency' => '$', 'currency_code' => 'SGD', 'flag' => 'countries/32x32/sg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'nationality' => 'Sint Maarten', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/sx.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Slovakia', 'code' => 'SK', 'nationality' => 'Slovak', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/sk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Slovenia', 'code' => 'SI', 'nationality' => 'Slovenian, Slovene', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/si.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'nationality' => 'Solomon Island', 'currency' => 'Si$', 'currency_code' => 'SBD', 'flag' => 'countries/32x32/sb.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Somalia', 'code' => 'SO', 'nationality' => 'Somalian', 'currency' => 'Sh', 'currency_code' => 'SOS', 'flag' => 'countries/32x32/so.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'South Africa', 'code' => 'ZA', 'nationality' => 'South African', 'currency' => 'R', 'currency_code' => 'ZAR', 'flag' => 'countries/32x32/za.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'nationality' => 'South Georgia or South Sandwich Islands', 'currency' => 'GEL', 'currency_code' => 'GEL', 'flag' => 'countries/32x32/gs.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'South Sudan', 'code' => 'SS', 'nationality' => 'South Sudanese', 'currency' => '£', 'currency_code' => 'SSP', 'flag' => 'countries/32x32/ss.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Spain', 'code' => 'ES', 'nationality' => 'Spanish', 'currency' => '€', 'currency_code' => 'EUR', 'flag' => 'countries/32x32/es.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'nationality' => 'Sri Lankan', 'currency' => 'Rs', 'currency_code' => 'LKR', 'flag' => 'countries/32x32/lk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Sudan', 'code' => 'SD', 'nationality' => 'Sudanese', 'currency' => 'ج.س.', 'currency_code' => 'SDG', 'flag' => 'countries/32x32/sd.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Suriname', 'code' => 'SR', 'nationality' => 'Surinamese', 'currency' => '$', 'currency_code' => 'SRD', 'flag' => 'countries/32x32/sr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'nationality' => 'Svalbard', 'currency' => 'Kr', 'currency_code' => 'NOK', 'flag' => 'countries/32x32/sj.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Swaziland', 'code' => 'SZ', 'nationality' => 'Swazi', 'currency' => 'L', 'currency_code' => 'SZL', 'flag' => 'countries/32x32/sz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Sweden', 'code' => 'SE', 'nationality' => 'Swedish', 'currency' => 'Kr', 'currency_code' => 'SEK', 'flag' => 'countries/32x32/se.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Switzerland', 'code' => 'CH', 'nationality' => 'Swiss', 'currency' => 'Fr.', 'currency_code' => 'CHF', 'flag' => 'countries/32x32/ch.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'nationality' => 'Syrian', 'currency' => 'LS', 'currency_code' => 'SYP', 'flag' => 'countries/32x32/es.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Taiwan', 'code' => 'TW', 'nationality' => 'Chinese, Taiwanese', 'currency' => '$', 'currency_code' => 'TWD', 'flag' => 'countries/32x32/tw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'nationality' => 'Tajikistani', 'currency' => 'SM', 'currency_code' => 'TJS', 'flag' => 'countries/32x32/tj.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'nationality' => 'Tanzanian', 'currency' => 'TSh', 'currency_code' => 'TZS', 'flag' => 'countries/32x32/tz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Thailand', 'code' => 'TH', 'nationality' => 'Thai', 'currency' => '฿', 'currency_code' => 'THB', 'flag' => 'countries/32x32/th.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'nationality' => 'Timorese', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/tl.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Togo', 'code' => 'TG', 'nationality' => 'Togolese', 'currency' => 'CFA', 'currency_code' => 'XOF', 'flag' => 'countries/32x32/tg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Tokelau', 'code' => 'TK', 'nationality' => 'Tokelauan', 'currency' => '$', 'currency_code' => 'NZD', 'flag' => 'countries/32x32/tk.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Tonga', 'code' => 'TO', 'nationality' => 'Tongan', 'currency' => 'T$', 'currency_code' => 'TOP', 'flag' => 'countries/32x32/es.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'nationality' => 'Trinidadian or Tobagonian', 'currency' => '$', 'currency_code' => 'TTD', 'flag' => 'countries/32x32/tt.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Tunisia', 'code' => 'TN', 'nationality' => 'Tunisian', 'currency' => 'DT', 'currency_code' => 'TND', 'flag' => 'countries/32x32/tn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Turkey', 'code' => 'TR', 'nationality' => 'Turkish', 'currency' => '₺', 'currency_code' => 'TRY', 'flag' => 'countries/32x32/tr.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'nationality' => 'Turkmen', 'currency' => 'T', 'currency_code' => 'TMT', 'flag' => 'countries/32x32/tm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'nationality' => 'Turks and Caicos Island', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/tc.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Tuvalu', 'code' => 'TV', 'nationality' => 'Tuvaluan', 'currency' => '$', 'currency_code' => 'AUD', 'flag' => 'countries/32x32/tv.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Uganda', 'code' => 'UG', 'nationality' => 'Ugandan', 'currency' => 'USh', 'currency_code' => 'UGX', 'flag' => 'countries/32x32/ug.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Ukraine', 'code' => 'UA', 'nationality' => 'Ukrainian', 'currency' => '₴', 'currency_code' => 'UAH', 'flag' => 'countries/32x32/ua.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'nationality' => 'Emirati, Emirian, Emiri', 'currency' => 'د.إ', 'currency_code' => 'AED', 'flag' => 'countries/32x32/ae.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'United Kingdom', 'code' => 'GB', 'nationality' => 'British, UK', 'currency' => '£', 'currency_code' => 'GBP', 'flag' => 'countries/32x32/gb.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'United States', 'code' => 'US', 'nationality' => 'American', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/us.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'nationality' => 'American', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/um.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Uruguay', 'code' => 'UY', 'nationality' => 'Uruguayan', 'currency' => '$', 'currency_code' => 'UYU', 'flag' => 'countries/32x32/uy.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'nationality' => 'Uzbekistani, Uzbek', 'currency' => "so'm", 'currency_code' => 'UZS', 'flag' => 'countries/32x32/uz.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Vanuatu', 'code' => 'VU', 'nationality' => 'Vanuatuan', 'currency' => 'VT', 'currency_code' => 'VUV', 'flag' => 'countries/32x32/vu.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'nationality' => 'Venezuelan', 'currency' => 'Bs', 'currency_code' => 'VES', 'flag' => 'countries/32x32/ve.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Viet Nam', 'code' => 'VN', 'nationality' => 'Vietnamese', 'currency' => '₫', 'currency_code' => 'VND', 'flag' => 'countries/32x32/vn.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'nationality' => 'British Virgin Island', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/vg.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'nationality' => 'U.S. Virgin Island', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/vi.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'nationality' => 'Wallis and Futuna, Wallisian or Futunan', 'currency' => '₣', 'currency_code' => 'XPF', 'flag' => 'countries/32x32/wf.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Western Sahara', 'code' => 'EH', 'nationality' => 'Sahrawi, Sahrawian, Sahraouian', 'currency' => 'DH', 'currency_code' => 'MAD', 'flag' => 'countries/32x32/eh.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Yemen', 'code' => 'YE', 'nationality' => 'Yemeni', 'currency' => '﷼', 'currency_code' => 'YER', 'flag' => 'countries/32x32/ye.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Zambia', 'code' => 'ZM', 'nationality' => 'Zambian', 'currency' => 'ZK', 'currency_code' => 'ZMW', 'flag' => 'countries/32x32/zm.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'nationality' => 'Zimbabwean', 'currency' => '$', 'currency_code' => 'USD', 'flag' => 'countries/32x32/zw.png', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
        ];

        foreach ($countries as &$country) {
            $country['phone_code'] = $phoneCodes[$country['code']] ?? null;
        }
        unset($country);

        DB::table('countries')->insert($countries);
    }
}
