<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        Schema::disableForeignKeyConstraints();
        // DB::table('roles')->truncate();
        // DB::table('user_roles')->truncate();
        DB::table('roles')->where('user_type', 'super_admin')->delete();
        DB::table('user_roles')->where('user_type', 'super_admin')->delete();
        Schema::enableForeignKeyConstraints();

        $name = 'Super Admin';
        $user_type = 'super_admin';

        DB::table('roles')->insert([
            'name' => $name,
            'user_type' => $user_type,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        $roles = [
            ['name' => $name, 'user_type' => $user_type, 'key' => 'company', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'company', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'company_delivery_site', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'company_delivery_site', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'company_delivery_site', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'company_delivery_site', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'semester', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'semester', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'semester', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'semester', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'subject', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'subject', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'subject', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'subject', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_resource', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_resource', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_resource', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_resource', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_assignment', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_assignment', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_assignment', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_assignment', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_fee', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_fee', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_fee', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'unit_fee', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_time_table', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_time_table', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_time_table', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_time_table', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'social_category', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'social_category', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'social_category', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'social_category', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_social', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_social', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_social', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_social', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_dashboard', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_intake', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_intake', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_intake', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_qualification', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_qualification', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_qualification', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_qualification', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_professional_development', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_professional_development', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_professional_development', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_professional_development', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_placement', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_placement', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_placement', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_placement', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'trainer_dashboard', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university_qualification', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university_qualification', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university_qualification', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'university_qualification', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource_category', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource_category', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource_category', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'resource_category', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'role', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'role', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'role', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'user', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'user', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'user', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'user', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'country', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'country', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment_grade', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment_grade', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment_grade', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment_grade', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment_submission', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'assignment_submission', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'setting', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'setting', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'online_class_group', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'online_class_group', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'online_class_group', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            /* ['name' => $name, 'user_type' => $user_type, 'key' => 'agent', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch_user', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch_user', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch_user', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_branch_user', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')], */
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course_fee', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course_fee', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course_fee', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course_fee', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_fee', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_fee', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_fee', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_course_fee', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course_fee', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course_fee', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course_fee', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_course_fee', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit_fee', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit_fee', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit_fee', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_intake_unit_fee', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'payment', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'payment', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'payment', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'payment', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_status', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_status', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_status', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_status', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'condition', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'condition', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'condition', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'condition', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'credit', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'credit', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'credit', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'credit', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'database_backup', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'database_backup', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email_template', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email_template', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email_template', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email_template', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email_user', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'email_user', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'template', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'template', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'intake_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            // ['name' => $name, 'user_type' => $user_type, 'key' => 'agent_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'due_pays_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'fee_received_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            // ['name' => $name, 'user_type' => $user_type, 'key' => 'commission_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'course_completion_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'marking_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'report_template', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'report_template', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'report_template', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_template', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_template', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_template', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'offer_template', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'classroom', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'classroom', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'classroom', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'document_type', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'document_type', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'document_type', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'document_type', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document_type', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document_type', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document_type', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document_type', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_document', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'lead', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'lead', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'lead', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'lead', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'zoho_lead', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'zoho_lead', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'zoho_lead', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'zoho_lead', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'location', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'location', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'location', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'location', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'fee_type', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'fee_type', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'fee_type', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'fee_type', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'marking_type', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'marking_type', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'marking_type', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'marking_type', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'ticket', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'ticket', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'ticket', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'ticket', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'chat', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'chat', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'chat', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'chat', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship_application', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship_application', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship_application', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'scholarship_application', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'analytics_dashboard', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'analytics_dashboard', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'analytics_dashboard', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'analytics_dashboard', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_risk_report', 'value' => 'view', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_risk_report', 'value' => 'add', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_risk_report', 'value' => 'edit', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => $name, 'user_type' => $user_type, 'key' => 'student_risk_report', 'value' => 'delete', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
        ];

        DB::table('user_roles')->insert($roles);
    }
}
